### ISSUE TITLE
Bug in Android-Slideshow, post Samsung March '21 Update

### ISSUE THREAD

**Issue by Coxo1** [ScreamingHawk/ScreamingHawk.github.io#9]
Hello,

There was a Samsung update in February/March for Android 11. After the update, Android-Slideshow cannot see files under a hidden folder. Technically a Samsung bug, but whatever they've done in that update, its broken A-S.

.hidden\.hidden - no files
.hidden\visible - no files
visbile\.hidden - no files
visible\visiblw - files

It can see directories fine, and navigate through them. Copying new files onto the device into the above folder structure doesnt show either as I thought it might be related to a damaged file catalog. This is wih all application/Samsung/Google updates installed.

Thanks for listening.

**Comment by ScreamingHawk** [comment]
Hi there. I assume this is for this project https://github.com/ScreamingHawk/android-slideshow ?

In the settings there is a `Show hidden files` option. Have you tried enabling that? If that doesn't help can you please re-raise this in the correct project. 

Thanks!!
